### ISSUE TITLE
Build errors related to recent nightly `Try` trait

### ISSUE THREAD

**Issue by denzp** [japaric/core64#1]
I got a bunch of errors when trying to build for **nvptx64** target with fresh nightly. Mainly they are about new [`Try` trait](https://github.com/rust-lang/rust/commit/dbc9d71b179bfe7e25704c17a574b8f579d3f776):

```
error[E0433]: failed to resolve. Could not find `Try` in `ops`
    --> /home/den/.cargo/git/checkouts/core64-98c99607e3b29655/4304271/fmt/mod.rs:1546:9
     |
1546 |         f.write_char('\'')?;
     |         -------------------
     |         |
     |         Could not find `Try` in `ops`
     |         in this macro invocation
```
Is it safe to pull recent sources from rust upstream, remove `i128` and make a PR? I'm afraid, it might break support of stable and beta.

**Comment by japaric** [comment]
> Is it safe to pull recent sources from rust upstream, remove i128 and make a PR?

Yes, that'd be OK. I didn't design this repo for upgradability though so that may require quite a bit of work.

> I'm afraid, it might break support of stable and beta.

You can't build this crate with stable or beta because it makes use of unstable features. (In general Xargo only works with the nightly and dev channel).

**Comment by denzp** [comment]
Ok, I see, thanks :) I prepared the PR.
